// Generated by scripts/generate-node-sdk-declarations.mjs from the Node-owned v1 contract projection.
export type KasbExecutionContext = {
    readonly signal?: AbortSignal;
};
export type SearchStandardsInput = {
    readonly keyword: string;
    readonly sort?: "relevance" | "match-count" | "std-num" | "title" | undefined;
    readonly limit?: number | undefined;
};
export type SearchStandardsResult = {
    readonly references: {
        readonly searchUrl: string;
    };
    readonly result: {
        readonly request: {
            readonly sort: "relevance" | "match-count" | "std-num" | "title";
            readonly limit: number;
            readonly keyword: string;
        };
        readonly totalMatchCount: number;
        readonly totalStandardCount: number;
        readonly returnedCount: number;
        readonly standards: readonly {
            readonly stdNum: string;
            readonly standardTitle?: string | undefined;
            readonly standardKind?: string | undefined;
            readonly matchCount: number;
            readonly references: {
                readonly apiUrl: string;
            };
            readonly nextActions: {
                readonly getStandardStructure: {
                    readonly input: {
                        readonly stdNum: string;
                    };
                    readonly operation: "get-standard-structure";
                };
            };
        }[];
        readonly suggestedKeywords: readonly string[];
    };
    readonly metadata: {
        readonly fetchedAt: string;
        readonly source: {
            readonly system: "kasb";
            readonly endpoint: string;
        };
        readonly sourceBehavior: {
            readonly observationStatus: "observed";
            readonly apiBase: "https://db.kasb.or.kr/api";
        };
        readonly completeness: "complete" | "partial";
        readonly content?: {
            readonly htmlFields?: readonly string[] | undefined;
            readonly textFields?: readonly string[] | undefined;
            readonly notes?: readonly string[] | undefined;
        } | undefined;
    };
    readonly warnings: readonly {
        readonly code: "truncated_results" | "source_metadata_incomplete";
        readonly message: string;
    }[];
};
export type GetStandardStructureInput = {
    readonly stdNum: string;
    readonly keyword?: string | undefined;
};
export type GetStandardStructureResult = {
    readonly references: {
        readonly stdNum: string;
        readonly structureUrl: string;
    };
    readonly result: {
        readonly request: {
            readonly keyword?: string | undefined;
            readonly stdNum: string;
        };
        readonly returnedCount: number;
        readonly sections: readonly {
            readonly sort?: number | undefined;
            readonly indexDocumentId: string;
            readonly title: string;
            readonly stdNum: string;
            readonly ref: string;
            readonly level: number;
            readonly documentType?: string | undefined;
            readonly parentDocumentIds: readonly string[];
        }[];
    };
    readonly metadata: {
        readonly fetchedAt: string;
        readonly source: {
            readonly system: "kasb";
            readonly endpoint: string;
        };
        readonly sourceBehavior: {
            readonly observationStatus: "observed";
            readonly apiBase: "https://db.kasb.or.kr/api";
        };
        readonly completeness: "complete" | "partial";
        readonly content?: {
            readonly htmlFields?: readonly string[] | undefined;
            readonly textFields?: readonly string[] | undefined;
            readonly notes?: readonly string[] | undefined;
        } | undefined;
    };
    readonly warnings: readonly {
        readonly code: "source_metadata_incomplete" | "search_filtered_structure";
        readonly message: string;
    }[];
};
export type GetSectionInput = {
    readonly stdNum: string;
    readonly keyword?: string | undefined;
    readonly indexDocumentId?: string | undefined;
    readonly ref?: string | undefined;
};
export type GetSectionResult = {
    readonly references: {
        readonly indexDocumentId: string;
        readonly stdNum: string;
        readonly standardTitle?: string | undefined;
        readonly standardKind?: string | undefined;
        readonly sectionTitle?: string | undefined;
        readonly sectionRef?: string | undefined;
        readonly sectionUrl: string;
    };
    readonly result: {
        readonly request: {
            readonly keyword?: string | undefined;
            readonly indexDocumentId?: string | undefined;
            readonly stdNum: string;
            readonly ref?: string | undefined;
        };
        readonly section: {
            readonly sort?: number | undefined;
            readonly indexDocumentId: string;
            readonly title: string;
            readonly stdNum: string;
            readonly standardTitle?: string | undefined;
            readonly standardKind?: string | undefined;
            readonly ref?: string | undefined;
            readonly level?: number | undefined;
        };
        readonly clauses: readonly {
            readonly sort?: number | undefined;
            readonly indexDocumentId: string;
            readonly title?: string | undefined;
            readonly stdNum: string;
            readonly kind: "title" | "paragraph" | "unknown";
            readonly uniqueKey?: string | undefined;
            readonly paraNum?: string | undefined;
            readonly paraContent?: string | undefined;
            readonly fullContent?: string | undefined;
            readonly faqDocNumbers?: string | undefined;
            readonly faqCount?: number | undefined;
        }[];
    };
    readonly metadata: {
        readonly fetchedAt: string;
        readonly source: {
            readonly system: "kasb";
            readonly endpoint: string;
        };
        readonly sourceBehavior: {
            readonly observationStatus: "observed";
            readonly apiBase: "https://db.kasb.or.kr/api";
        };
        readonly completeness: "complete" | "partial";
        readonly content?: {
            readonly htmlFields?: readonly string[] | undefined;
            readonly textFields?: readonly string[] | undefined;
            readonly notes?: readonly string[] | undefined;
        } | undefined;
    };
    readonly warnings: readonly {
        readonly code: "ambiguous_ref_resolved" | "empty_section" | "partial_clause_normalization";
        readonly message: string;
    }[];
};
export type GetParagraphInput = {
    readonly stdNum: string;
    readonly paraNum: string;
};
export type GetParagraphResult = {
    readonly references: {
        readonly indexDocumentId: string;
        readonly stdNum: string;
        readonly standardTitle?: string | undefined;
        readonly standardKind?: string | undefined;
        readonly uniqueKey: string;
        readonly paraNum: string;
        readonly sectionTitle?: string | undefined;
        readonly sectionRef?: string | undefined;
        readonly paragraphUrl: string;
    };
    readonly result: {
        readonly request: {
            readonly stdNum: string;
            readonly paraNum: string;
        };
        readonly paragraph: {
            readonly sort?: number | undefined;
            readonly indexDocumentId: string;
            readonly stdNum: string;
            readonly standardTitle?: string | undefined;
            readonly standardKind?: string | undefined;
            readonly uniqueKey: string;
            readonly paraNum: string;
            readonly paraContent: string;
            readonly fullContent: string;
            readonly faqDocNumbers?: string | undefined;
            readonly faqCount?: number | undefined;
            readonly sectionTitle?: string | undefined;
            readonly sectionRef?: string | undefined;
        };
    };
    readonly metadata: {
        readonly fetchedAt: string;
        readonly source: {
            readonly system: "kasb";
            readonly endpoint: string;
        };
        readonly sourceBehavior: {
            readonly observationStatus: "observed";
            readonly apiBase: "https://db.kasb.or.kr/api";
        };
        readonly completeness: "complete" | "partial";
        readonly content?: {
            readonly htmlFields?: readonly string[] | undefined;
            readonly textFields?: readonly string[] | undefined;
            readonly notes?: readonly string[] | undefined;
        } | undefined;
    };
    readonly warnings: readonly {
        readonly code: "paragraph_metadata_incomplete";
        readonly message: string;
    }[];
};
export type SearchQnaInput = {
    readonly keyword: string;
    readonly rows?: number | undefined;
    readonly from?: string | undefined;
    readonly page?: number | undefined;
    readonly types?: string | undefined;
    readonly sortDate?: "asc" | "desc" | undefined;
    readonly to?: string | undefined;
};
export type SearchQnaResult = {
    readonly references: {
        readonly searchUrl: string;
    };
    readonly result: {
        readonly request: {
            readonly rows: number;
            readonly keyword: string;
            readonly from?: string | undefined;
            readonly page: number;
            readonly types?: string | undefined;
            readonly sortDate?: "asc" | "desc" | undefined;
            readonly to?: string | undefined;
        };
        readonly returnedCount: number;
        readonly suggestedKeywords: readonly string[];
        readonly items: readonly {
            readonly title: string;
            readonly references: {
                readonly qnaUrl: string;
            };
            readonly docNumber: string;
            readonly type: number;
            readonly typeLabel: string;
            readonly snippet: string;
            readonly tags: readonly string[];
            readonly deprecated: boolean;
            readonly contentLink?: string | undefined;
            readonly publishDate?: string | undefined;
            readonly prefix?: string | undefined;
        }[];
        readonly totalCount: number;
        readonly totalPages: number;
        readonly hasNextPage: boolean;
        readonly paginationStatus: "known" | "estimated";
        readonly countByType: {
            readonly [x: string]: number;
        };
        readonly typeLabels: {
            readonly [x: string]: string;
        };
    };
    readonly metadata: {
        readonly fetchedAt: string;
        readonly source: {
            readonly system: "kasb";
            readonly endpoint: string;
        };
        readonly sourceBehavior: {
            readonly observationStatus: "observed";
            readonly apiBase: "https://db.kasb.or.kr/api";
        };
        readonly completeness: "complete" | "partial";
        readonly content?: {
            readonly htmlFields?: readonly string[] | undefined;
            readonly textFields?: readonly string[] | undefined;
            readonly notes?: readonly string[] | undefined;
        } | undefined;
    };
    readonly warnings: readonly {
        readonly code: "source_metadata_incomplete";
        readonly message: string;
    }[];
};
export type GetQnaInput = {
    readonly docNumber: string;
    readonly keyword?: string | undefined;
};
export type GetQnaResult = {
    readonly references: {
        readonly docNumber: string;
        readonly qnaUrl: string;
    };
    readonly result: {
        readonly request: {
            readonly keyword?: string | undefined;
            readonly docNumber: string;
        };
        readonly qna: {
            readonly title: string;
            readonly fullContent: string;
            readonly docNumber: string;
            readonly type: number;
            readonly typeLabel: string;
            readonly tags: readonly string[];
            readonly deprecated: boolean;
            readonly contentLink?: string | undefined;
            readonly publishDate?: string | undefined;
            readonly id?: number | undefined;
            readonly reference?: string | undefined;
            readonly contentHtml?: string | undefined;
            readonly relStds?: string | undefined;
            readonly prevDocNumber?: string | undefined;
            readonly nextDocNumber?: string | undefined;
        };
    };
    readonly metadata: {
        readonly fetchedAt: string;
        readonly source: {
            readonly system: "kasb";
            readonly endpoint: string;
        };
        readonly sourceBehavior: {
            readonly observationStatus: "observed";
            readonly apiBase: "https://db.kasb.or.kr/api";
        };
        readonly completeness: "complete" | "partial";
        readonly content?: {
            readonly htmlFields?: readonly string[] | undefined;
            readonly textFields?: readonly string[] | undefined;
            readonly notes?: readonly string[] | undefined;
        } | undefined;
    };
    readonly warnings: readonly {
        readonly code: "source_metadata_incomplete";
        readonly message: string;
    }[];
};
export type KasbFailureCode = "invalid_input" | "not_found" | "source_unavailable" | "source_changed" | "partial_retrieval" | "internal_failure";
export type KasbFailureDetails = {
    readonly code: KasbFailureCode;
    readonly message: string;
    readonly retryable: boolean;
    readonly parameter?: string;
    readonly sourceUrl?: string;
};
export declare class KasbFailure extends Error {
    readonly name: "KasbFailure";
    readonly code: KasbFailureCode;
    readonly retryable: boolean;
    readonly parameter?: string;
    readonly sourceUrl?: string;
    constructor(details: KasbFailureDetails);
}
export declare function searchStandards(input: SearchStandardsInput, context?: KasbExecutionContext): Promise<SearchStandardsResult>;
export declare function getStandardStructure(input: GetStandardStructureInput, context?: KasbExecutionContext): Promise<GetStandardStructureResult>;
export declare function getSection(input: GetSectionInput, context?: KasbExecutionContext): Promise<GetSectionResult>;
export declare function getParagraph(input: GetParagraphInput, context?: KasbExecutionContext): Promise<GetParagraphResult>;
export declare function searchQna(input: SearchQnaInput, context?: KasbExecutionContext): Promise<SearchQnaResult>;
export declare function getQna(input: GetQnaInput, context?: KasbExecutionContext): Promise<GetQnaResult>;
